### ISSUE TITLE
JavaFX example as a Netbeans project

### ISSUE THREAD

**Issue by njss** [EyeTribe/tet-java-client#10]
I've tried to open the gradle project on Netbeans but it doesn't work at all.
Can you make available a Netbeans project instead?

thank you.

**Comment by arnebp** [comment]
Hi Nelson 

Our Java projects use Gradle in order to stay IDE independent. We will therefore not make the projects specific to NetBeans, IntelliJ, Eclipse or any other Java IDEs. 

I would suggest that you post this request in our developer forum instead. Here, developers that use NetBeans such as yourself would surely be able to assist you. http://theeyetribe.com/forum/viewforum.php?f=24&sid=334f3bb63af68b9bdbc1c67eec3358d9

Please be sure to include the errors reported by NetBeans in your post.

**Comment by arnebp** [comment]
Hi @njss 

Could you have another go at the NetBeans Gradle import using this fork https://github.com/arnebp/tet-java-client ? Some minor changes may have fixed the issue you were experiencing. Please let me know if this fixes your issues.

**Comment by njss** [comment]
Sorry for not replying before. I am currently on a big trip, I will try
again when I am back to the office. Thank you for your reply.
